export enum Category {
  WebDevelopment = "Web Development",
  MachineLearning = "Machine Learning",
  DigitalMarketing = "Digital Marketing",
  Photography = "Photography",
  Python = "Python",
  Business = "Business",
  Creative = "Creative",
  FrontEnd = "Front-End",
  BackEnd = "Back-End",
  DataScience = "Data Science",
  Beginner = "Beginner",
  Intermediate = "Intermediate",
  Advanced = "Advanced",
  AI = "AI",
  DeepLearning = "Deep Learning",
}
